{
 "title": "MicroProfile Metrics Endpoint Monitoring",
 "description": "MicroProfile Metrics Endpoint Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "serviceID",
    "label": "ServiceID",
    "query": "label_values(base_cpu_systemLoadAverage{namespace=\"$namespace\"}, job)"
   },
   {
    "name": "pod",
    "query": "label_values(base_cpu_systemLoadAverage{job=\"$serviceID\"}, pod)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"$serviceID\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": " base_jvm_uptime_seconds Displays the uptime of the JVM in milliseconds.",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "base_jvm_uptime_seconds{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "GC Copy & Mark Sweep Total",
   "type": "graph",
   "description": "base_gc_total_total Displays the total number of collections that have occurred. This attribute lists -1 if the collection count is undefined for this collector.",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_gc_total{pod=\"$pod\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{pod=\"$pod\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{pod=\"$pod\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=\"$pod\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Heap Sizes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{pod=\"$pod\"}",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "base_memory_committedHeap_bytes{pod=\"$pod\"}",
     "legendFormat": "Commited Heap"
    },
    {
     "expr": "base_memory_maxHeap_bytes{pod=\"$pod\"}",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Non Heap Sizes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memory_usedNonHeap_bytes{pod=\"$pod\"}",
     "legendFormat": "Used Non Heap"
    },
    {
     "expr": "vendor_memory_usedNonHeap_bytes{pod=\"$pod\"}",
     "legendFormat": "Commited Non Heap"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{pod=\"$pod\"}",
     "legendFormat": "Thread Count"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=\"$pod\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{pod=\"$pod\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{pod=\"$pod\", type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Production Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (product) (application_click_klaassen_ProductMetricsService_hardware_rate_per_second)",
     "legendFormat": "{{product}}"
    }
   ]
  },
  {
   "title": "Production Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (product) (application_click_klaassen_ProductMetricsService_hardware_total)",
     "legendFormat": "{{product}}"
    }
   ]
  }
 ]
}